include:
  - _framework
  - _bin

author: cyb3rdog
theme: jekyll-theme-midnight
show_downloads: true
show_repository: true
app_installer_url: "https://github.com/cyb3rdog/Cyb3rVector/releases/download/v0.9.48/Cyb3rVector-v0.9.48.msi"
app_portable_url: "https://github.com/cyb3rdog/Cyb3rVector/releases/download/v0.9.48/Cyb3rVector-v0.9.48.zip"
gems:
  - jekyll-redirect-from
  - jekyll-target-blank
  - jekyll-paginate
  - jemoji
plugins:
  - jekyll-redirect-from
  - jekyll-target-blank
  - jemoji
