include:
  - _framework
  - _bin

author: cyb3rdog
theme: jekyll-theme-midnight
show_downloads: true
show_repository: true
google_analytics: "UA-194177404-2"
app_installer_url: "http://vector.phact.cz/download/Cyb3rVector-v0.9.57.msi"
app_portable_url: "http://vector.phact.cz/download/Cyb3rVector-v0.9.57.zip"
gems:
  - jekyll-redirect-from
  - jekyll-target-blank
  - jekyll-paginate
  - jemoji
plugins:
  - jekyll-redirect-from
  - jekyll-target-blank
  - jemoji
